#Group 27
#Venkat Nalla Siddartha Reddy                2016A7PS0030P
#Arnav Sailesh                               2016A7PS0054P
#Gunraj Singh                                2016A7PS0085P
#Aashish Singh                               2016A7PS0683P

all:
	gcc -g -o compiler driver.c lexer.c parser.c keyword_table.c nary_tree.c stack.c ast.c symbol_table.c type_checker.c semantic_analyzer.c printer.c error_handler.c code_gen.c
